[project]
name = "ebook-convert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Robert Schroll", email = "rschroll@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ebook-convert = "calibre.ebooks.conversion.cli:main"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "calibre"
